### ISSUE TITLE
Error running Inspector

### ISSUE THREAD

**Issue by rlorigro** [Maggi-Chen/Inspector#5]
Hi, 

We are trying to run Inspector, and we installed using the following commands:

```
virtualenv --python=/usr/bin/python2.7 inspector_env
pip install pysam
pip install statsmodels --no-use-pep517
```
And we get this error involving numpy:

```
(inspector_env) ubuntu@ip-172-31-23-69:~/software/Inspector$ ./inspector.py -c /home/ubuntu/data/cuttlefish/assembly/run1/Assembly.fasta -r /home/ubuntu/data/cuttlefish/reads/cuttlefish_Guppy_5.0.7_sup.fastq /home/ubuntu/data/cuttlefish/reads/09_28_21_R941_CF5mg_Guppy_5.0.11_prom_sup.fastq -o inspector_out/ --datatype nanopore -t 40
Traceback (most recent call last):
 File "./inspector.py", line 70, in <module>
  import denovo_baseerror
 File "/home/ubuntu/software/Inspector/denovo_baseerror.py", line 3, in <module>
  import statsmodels.stats.proportion
 File "/home/ubuntu/software/Inspector/inspector_env/lib/python2.7/site-packages/statsmodels/stats/__init__.py", line 1, in <module>
  from statsmodels.tools._testing import PytestTester
 File "/home/ubuntu/software/Inspector/inspector_env/lib/python2.7/site-packages/statsmodels/tools/__init__.py", line 1, in <module>
  from .tools import add_constant, categorical
 File "/home/ubuntu/software/Inspector/inspector_env/lib/python2.7/site-packages/statsmodels/tools/tools.py", line 8, in <module>
  from statsmodels.compat.python import lzip, lmap
 File "/home/ubuntu/software/Inspector/inspector_env/lib/python2.7/site-packages/statsmodels/compat/__init__.py", line 1, in <module>
  from statsmodels.tools._testing import PytestTester
 File "/home/ubuntu/software/Inspector/inspector_env/lib/python2.7/site-packages/statsmodels/tools/_testing.py", line 11, in <module>
  from statsmodels.compat.pandas import assert_equal
 File "/home/ubuntu/software/Inspector/inspector_env/lib/python2.7/site-packages/statsmodels/compat/pandas.py", line 4, in <module>
  import numpy as np
 File "/home/ubuntu/software/Inspector/inspector_env/lib/python2.7/site-packages/statsmodels/compat/numpy.py", line 46, in <module>
  NP_LT_114 = LooseVersion(np.__version__) < LooseVersion('1.14')
AttributeError: 'module' object has no attribute '__version__'
```
Can you help with this?

Thanks

**Comment by Maggi-Chen** [comment]
Hello,

It seems like there is something wrong with package statsmodels. Latest versions of statsmodels (since v0.11.0) do not support python 2.7. Can you try installing version 0.10.1 with `pip install statsmodels==0.10.1` and see if it works?

Bests,
Maggi

**Comment by rlorigro** [comment]
I see. We tried this and it worked, thank you.
